spring.application.name=erp

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/college_erp?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Server Port
server.port=8095
server.address=0.0.0.0
logging.level.org.springframework.security=TRACE
server.error.whitelabel.enabled=false
server.error.include-stacktrace=never

# JWT Configuration
erp.jwt.secret=9a4fba3663a89301140089a502e1de7f884aef5aa9de8b71d497c234a41d0ffc8f35c5c8de9359e19e71ecba3a8c1de6c2975927c7a52f9c756b50e30925e0a2
erp.jwt.expiration-ms=86400000
erp.jwt.cookie-name=erp-jwt
